### ISSUE TITLE
Проблема с совместимостью

### ISSUE THREAD

**Issue by harry-holland** [morgandusty/UnionLogs-2021#1]
Привет!
При установке скрипта логов на свой сервер столкнулся с некоторыми ошибками. Основная проблема заключается при регистрации. Когда я ввожу все необходимые данные и нажимаю на кнопку "регистрация", меня перекидывает на главную страницу. Так же вверху страницы отображается сообщение с ошибкой Warning: mysqli_select_db() expects exactly 2 parameters, 1 given in /www/wwwroot/example.com/includes/connection.php on line 8. Я думаю, что скрипт несовместим с моей конфигурацией базы данных. Как мне исправить проблему? Надеюсь на помощь. Заранее спасибо.

Моя конфигурация:
Сервер баз данных
Сервер: Localhost via UNIX socket
Тип сервера: MySQL
Версия сервера: 8.0.23 - Source distribution

Веб-сервер
nginx/1.19.7
Версия клиента базы данных: libmysql - mysqlnd 7.4.16
Версия PHP: 7.4.16

Так же другие ошибки:
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /www/wwwroot/example.com/logsall.php on line 25
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /www/wwwroot/example.com/logsdbtype1.php on line 30
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /www/wwwroot/example.com/logsdbtype3.php on line 31 
и др.

**Comment by morgandusty** [comment]
**На рассмотрении...**

**Comment by morgandusty** [comment]
база test.sql включает в себя "логин и пароль" - test и да, база подключается в includes в файлах (con_logs - логи сервера, constants - это наша база test.sql)
регистрация отключается через register.php

_(Если вам не помогло, дайте знать)_

**Comment by harry-holland** [comment]
Вопрос неактуален уже больше года. И да, ответ СОВСЕМ НЕ ПОМОГ, потому что я не это пытался узнать) Впредь автору желаю ВНИМАТЕЛЬНЕЕ читать вопросы и вникать в суть проблемы. Закрыто.

**Comment by morgandusty** [comment]
Я никому не обещал помогать с ошибками, ибо у каждого свой мод и свой язык кодинга. Впредь советую писать более подробнее и прикладывать то какие у вас базы-данных ранее использованы, закрыто.
